apiVersion: v1
kind: Pod
metadata:
  name: dbaas-test-pod
  labels:
    app: dbaas-test
spec:
  containers:
    - name: dbaas-test
      image: sanchpet/dbaas-test:v0.0.1
      env:
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_TIMEOUT_READ
          value: "3s"
        - name: SERVER_TIMEOUT_WRITE
          value: "5s"
        - name: SERVER_TIMEOUT_IDLE
          value: "5s"
        - name: SERVER_DEBUG
          value: "true"
