name: Publish Helm Chart to Docker Hub OCI on Release

on:
  release:
    types: [published]

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    env:
      CHART_DIR: helm/charts/dbaas-api
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      OCI_REGISTRY: oci://registry-1.docker.io/${{ vars.DOCKERHUB_USERNAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm chart
        run: helm package $CHART_DIR

      - name: Login to Docker Hub OCI registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login registry-1.docker.io -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push chart to Docker Hub OCI
        run: |
          CHART_TGZ=$(ls dbaas-api-*.tgz | head -n1)
          helm push $CHART_TGZ $OCI_REGISTRY
